# Site settings
title: Compre.io
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: compreoficial
instagram_username: compre.io

# Build settings
markdown: kramdown

include: ["_assets"]
